const express =require('express')
const res =require('./register')
const logins =require('./loing')
const rotes=require('./routes')
const app =express()
const db =require('./db')
const cors =require('cors')
app.use(cors())
app.use('/register',res)
app.use('/login',logins)
app.use('/p',rotes)
app.listen(3000,async ()=>{
    await db()
    console.log('port connected')
})